# Volumes
export ARCHIVE="/Volumes/Archive"
export AUDIO="/Volumes/Audio"
export MEDIA="/Volumes/Media"
export PORTABLE="/Volumes/Portable"
export VIDEO="/Volumes/Video"

# Folders
export DRIVE="$ARCHIVE/Drive"
export DOTFILES="$HOME/dotfiles"
export DOWNLOADS="$HOME/Downloads"
export MOBILE="$HOME/Library/Mobile\ Documents"
export PROJECTS="$AUDIO/Audio/Projects"
export SHARED="$DRIVE/Shared"
export WORK="$HOME/Work"

# ZSH settings
ZSH=$HOME/.oh-my-zsh
ZSH_THEME=""

# ZSH plugins
plugins=(git macos encode64 web-search last-working-dir git-flow-completion zsh-syntax-highlighting zsh-autosuggestions git-open brew omz-git zsh-vi-mode)

# ZSH INTERACTIVE CD
source $ZSH/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh
export PATH="/usr/local/sbin:$PATH"

# SOURCES
source $ZSH/oh-my-zsh.sh

# Load modular aliases
for alias_file in $DOTFILES/shell/aliases/*.sh; do
  source "$alias_file"
done

# Load modular functions
for func_file in $DOTFILES/shell/functions/*.sh; do
  source "$func_file"
done

# EDITOR
export VISUAL=nvim
export EDITOR="$VISUAL"

# MAN PAGES
export MANPAGER='nvim +Man!'

# HISTORY
export HISTCONTROL=ignorespace

# BINDINGS
bindkey '^ ' autosuggest-accept
bindkey -M menuselect '^[[Z' reverse-menu-complete
bindkey -M viins 'jj' vi-cmd-mode

export ZVM_VI_ESCAPE_BINDKEY=jk
ZVM_CURSOR_STYLE_ENABLED=false
zvm_after_init_commands+=('bindkey "^ " autosuggest-accept')

# PATHS
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.local/bin
export PATH="/usr/local/opt/node@22/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"

# CUSTOM
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

## POWERLINE
# Removed deprecated Python 2.7 reference
# Powerline is now handled by Starship prompt (see below)

## RTV
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

fpath=(~/.zsh/completions $fpath)

autoload -U compinit && compinit

## FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Initialise rbenv
eval "$(rbenv init -)"

# Initialise Starship
eval "$(starship init zsh)"

source $HOME/Library/Preferences/org.dystroy.broot/launcher/bash/br
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

eval $(thefuck --alias)

# Supress Ruby warnings
export RUBYOPT=-W0
eval "$(/opt/homebrew/bin/brew shellenv)"

# 1Password CLI integration
export OP_BIOMETRIC_UNLOCK_ENABLED=true

# BEETS ENV VARIABLE
export BEETSDIR="$HOME/.config/beets/"

# Warp Terminal settings for ZSH
if [[ $TERM_PROGRAM == "WarpTerminal" ]]; then
  printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'
fi

# cyrus-sasl homebrew version to fix neomutt
export PATH="/opt/homebrew/opt/cyrus-sasl/sbin:$PATH"

# Day One CLI
export DAYONE_APP_PATH="/Applications/Day One.app"

# fnm fast node manager (using fnm instead of nvm for better performance)
eval "$(fnm env --use-on-cd --shell zsh --version-file-strategy=recursive)"

# zoxide - smarter cd command
eval "$(zoxide init zsh)"

##########
# HISTORY
##########

HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

# Immediately append to history file:
setopt INC_APPEND_HISTORY

# Record timestamp in history:
setopt EXTENDED_HISTORY

# Expire duplicate entries first when trimming history:
setopt HIST_EXPIRE_DUPS_FIRST

# Dont record an entry that was just recorded again:
setopt HIST_IGNORE_DUPS

# Delete old recorded entry if new entry is a duplicate:
setopt HIST_IGNORE_ALL_DUPS

# Do not display a line previously found:
setopt HIST_FIND_NO_DUPS

# Dont record an entry starting with a space:
setopt HIST_IGNORE_SPACE

# Dont write duplicate entries in the history file:
setopt HIST_SAVE_NO_DUPS

# Share history between all sessions:
setopt SHARE_HISTORY

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY
