#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_frame_rate  120
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config window_border_width          4
yabai -m config window_border_radius         12
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on
yabai -m config window_border                off
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   06
yabai -m config layout                       bsp
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# float system preferences. Most of these just disable Yabai form resizing them.
yabai -m rule --add app="^1Password$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Archive Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Curve$" sticky=on layer=above manage=off
yabai -m rule --add app="^Console$" manage=off
yabai -m rule --add app="^DaVinci Resolve$" manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Fantastical$" manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^GIMP$" sticky=on layer=above manage=off
yabai -m rule --add app="^Google Drive$" sticky=on layer=above manage=off
yabai -m rule --add app="^Installer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Komplete Kontrol$" sticky=on layer=above manage=off
yabai -m rule --add app="^Live$" sticky=on layer=above manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Native Access$" manage=off
yabai -m rule --add app="^OBS$" sticky=on layer=above manage=off
yabai -m rule --add app="^Python$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^VCV Rack 2 Pro$" manage=off
yabai -m rule --add app="^iZotope Product Portal$" sticky=on layer=above manage=off
yabai -m rule --add app="^iZotope RX 10$" sticky=on layer=above manage=off
yabai -m rule --add app="^mpv$" sticky=on layer=above manage=off
# yabai -m rule --add app="^iTerm2$" manage=off
# yabai -m rule --add app="^WhatsApp$" manage=off
# yabai -m rule --add app="^Messages$" manage=off

echo "yabai configuration loaded.."
